### ISSUE TITLE
Error occurred when opening serial port: Port must be configured before it can be used.

### ISSUE THREAD

**Issue by Soundtoxin** [JonnyHaystack/haybox-cli#6]
I tried setting this up on two different machines. One GNU/Linux via pip and the other Windows via the exe from Releases. With both I get no output from `haybox devices` and from `haybox info` and `haybox config get` and most other commands I'm getting this error:
`Error occurred when opening serial port: Port must be configured before it can be used.`
Is this something I actually need to set up on my end or an issue with the program?
I am running version 0.1.0 from pip (not sure why it's old) and the latest release (0.1.4) on the Windows machine.
edit: I'm using my Open-Frame1, Pico-based controller.

**Comment by JonnyHaystack** [comment]
Hold button `RT2` (C-Down) on plugin. Also `haybox info` and `haybox config get` won't work without supplying the serial port for them to use.

**Comment by Soundtoxin** [comment]
On the GNU/Linux machine I have the following issue now:
```
2024-08-24T17:51:40,240813-05:00 usb 1-9.3.1: new full-speed USB device number 97 using xhci_hcd
2024-08-24T17:51:40,342659-05:00 usb 1-9.3.1: New USB device found, idVendor=2e8a, idProduct=000a, bcdDevice= 1.00
2024-08-24T17:51:40,342666-05:00 usb 1-9.3.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
2024-08-24T17:51:40,342668-05:00 usb 1-9.3.1: Product: Pico
2024-08-24T17:51:40,342670-05:00 usb 1-9.3.1: Manufacturer: Raspberry Pi
2024-08-24T17:51:40,342672-05:00 usb 1-9.3.1: SerialNumber: E66118C417909121
2024-08-24T17:51:40,352904-05:00 cdc_acm 1-9.3.1:1.0: ttyACM0: USB ACM device
brad@anpan:~/ > haybox devices
Device on ttyACM0:
Error occurred when opening serial port: [Errno 2] could not open port ttyACM0: [Errno 2] No such file or directory: 'ttyACM0'
brad@anpan:~/ > haybox config get ttyACM0
Usage: haybox config get [OPTIONS]
Try 'haybox config get -h' for help.

Error: Got unexpected extra argument (ttyACM0)
brad@anpan:~/ > haybox config get
Error occurred when opening serial port: Port must be configured before it can be used.
brad@anpan:~/ > haybox info ttyACM0
Usage: haybox info [OPTIONS]
Try 'haybox info -h' for help.

Error: Got unexpected extra argument (ttyACM0)
brad@anpan:~/ > haybox info /dev/ttyACM0
Usage: haybox info [OPTIONS]
Try 'haybox info -h' for help.

Error: Got unexpected extra argument (/dev/ttyACM0)
brad@anpan:~/ > ls /dev/tty*
/dev/tty    /dev/tty23  /dev/tty39  /dev/tty54      /dev/ttyS10  /dev/ttyS26
/dev/tty0   /dev/tty24  /dev/tty4   /dev/tty55      /dev/ttyS11  /dev/ttyS27
/dev/tty1   /dev/tty25  /dev/tty40  /dev/tty56      /dev/ttyS12  /dev/ttyS28
/dev/tty10  /dev/tty26  /dev/tty41  /dev/tty57      /dev/ttyS13  /dev/ttyS29
/dev/tty11  /dev/tty27  /dev/tty42  /dev/tty58      /dev/ttyS14  /dev/ttyS3
/dev/tty12  /dev/tty28  /dev/tty43  /dev/tty59      /dev/ttyS15  /dev/ttyS30
/dev/tty13  /dev/tty29  /dev/tty44  /dev/tty6       /dev/ttyS16  /dev/ttyS31
/dev/tty14  /dev/tty3   /dev/tty45  /dev/tty60      /dev/ttyS17  /dev/ttyS4
/dev/tty15  /dev/tty30  /dev/tty46  /dev/tty61      /dev/ttyS18  /dev/ttyS5
/dev/tty16  /dev/tty31  /dev/tty47  /dev/tty62      /dev/ttyS19  /dev/ttyS6
/dev/tty17  /dev/tty32  /dev/tty48  /dev/tty63      /dev/ttyS2   /dev/ttyS7
/dev/tty18  /dev/tty33  /dev/tty49  /dev/tty7       /dev/ttyS20  /dev/ttyS8
/dev/tty19  /dev/tty34  /dev/tty5   /dev/tty8       /dev/ttyS21  /dev/ttyS9
/dev/tty2   /dev/tty35  /dev/tty50  /dev/tty9       /dev/ttyS22
/dev/tty20  /dev/tty36  /dev/tty51  /dev/ttyprintk  /dev/ttyS23
/dev/tty21  /dev/tty37  /dev/tty52  /dev/ttyS0      /dev/ttyS24
/dev/tty22  /dev/tty38  /dev/tty53  /dev/ttyS1      /dev/ttyS25
brad@anpan:~/ > ls /dev/tty* | gi acm
```

I don't have the file in /dev that it supposedly maps to.

On the Windows machine I get this far:
```
.\haybox-cli-v0.1.4.exe devices
Device on COM5
    Device name: pico
    Firmware name: HayBox
    Firmware version: 3.0.0
```

but when I try `info COM5`, `info 5`, `info pico` I get `Error: Got unexpected extra argument (COM5)` and so on. So what is the syntax here?
Nevermind, checked source and I see I need `-d COM5`. Was not clear from the help output.

I see `config get -d COM5` outputs json to my shell, so do I redirect that to a file, edit it, then use `config set -d COM5 whatever.json`?

I tried redirecting with `> filename.json` then opened in nvim and did `:%s/_NO_REAC//` to make all `SOCD_2IP_NO_REAC` into `SOCD_2IP`, then saved and did `config set -d COM5 file.json`. It didn't like something about the file. Was about to ask what to do but decided to look at the source again. Saw the `config get` has a `-o` (output) option so then did it again with `config get -d COM5 -o config.json`, redid edits, set command again, and *that* time it worked. So beware anyone else trying to be clever about it, Windows redirection of the output must mangle something.
Finally did `reboot -d COM5 firmware` (starting to get the hang of this thing) to boot back into controller mode and tested on Gamepad Tester. Works just how I want now!

Thanks for the help and for your patience. In the early days here with light documentation I thought writing out my experience verbosely might help the next person trying to do this. I'm not gonna worry too much about it not working on my main PC for now since I got it working on something. I might just need to hop in my distro's IRC later and see if there's a way to get that missing /dev file made.

**Comment by JonnyHaystack** [comment]
Oh, yeah that is weird that the serial device isn't showing up for you on Linux. Glad you got the rest figured out though.
